### ISSUE TITLE
Add Federated SAP S/4HANA Roles to Your Launchpad Site

### ISSUE THREAD

**Issue by hubertdieleman** [sap-tutorials/Tutorials#17984]
Tutorials: https://developers.sap.com/tutorials/cp-launchpad-federation-consumption.html
--------------------------

Write here how you think we can improve the tutorial ...

I was able to follow all steps with the exception of step 5 -3 Click Default Identity Provider to access the role collection assignment for users coming from this identity provider.
In my trial account I am not able to access teh Default Identity provide. It is grayed out. The srult is that in the end I can see all tiles, but when opening a tile I get the error a1111111trial.authentication.us10.hana.ondemand.com refused to connect.

I there a work around?

**Comment by SibylleB** [comment]
Hi,
Thanks for bringing this up. The way to assign role collections changed recently and I need to adapt this tutorial. Please go to Security > Role Collections instead of Trust Configuration and click on your Role Collection there, then you can add your user in this place to assign it to the role collection. You might need to click the Edit button before you can enter a new user.
Hope that helps.
Best,
Sibylle
