### ISSUE TITLE
Access a Classic Schema from SAP Business Application Studio - don't access

### ISSUE THREAD

**Issue by KaydunovDenis** [sap-tutorials/Tutorials#17989]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-access-cross-container-schema.html
--------------------------

In a previous tutorial, we create DB: SharedDevKey@DM-hdidb-ws-jbhsf  
But this tutorial author uses:  ... Trial_TPJ... 
But we don't have it.

I try complete this tutorial using DB: SharedDevKey@DM-hdidb-ws-jbhsf  , but the step "Open SAP HANA Database Explorer "doesn't work.
My google chrome automatically entered a login: hanadb2
and a password: *****  
And this a magic. my login replace on HANADB2
and cath error, view on next screen:
![image](https://user-images.githubusercontent.com/23221641/148902260-979e0462-48e2-4cb3-9ca6-476377df9e1c.png)

I try run SQL queries, but I receive error: not enough rights.

**Comment by jung-thomas** [comment]
No you don't connect with your HDI container.  You connect with your dedicated DB instance. This is why we return to the SAP HANA Cloud tool in BTP Cockpit and use the Open SAP Database Explorer instead of opening it from Business Application Studio.  This will not only open the DB Explorer but will create a connection entry using your database login credentials (DBADMIN). 

Your browser it filling in credentials for you, but those aren't right for this system. Please supply the DBADMIN user and the correct password for DBADMIN which you created when you created your HANA Cloud instance.
