### ISSUE TITLE
Develop a Custom UI for an SAP S/4HANA Cloud Tenant

### ISSUE THREAD

**Issue by JTR7** [sap-tutorials/Tutorials#18006]
Tutorials: https://developers.sap.com/tutorials/abap-custom-ui-bas-develop-s4hc.html
--------------------------

In Step 4, i'm not able to connect to S4HC.

I've selected the respective system to which i have a destination. 

Defined the Service Path: https://my303372-api.s4hana.ondemand.com/sap/opu/odata/sap/API_EQUIPMENT
Also tried with a custom communication scenario "YY1_ Equipment_CDS" 

For the 1st service i've used same Inbound Comm User available in BTP Destination and Communication System (created automatically by BTP).

Used the password defined in the destination as in Communication System in S4HC this attribute is not visible. 

None of them worked and always saying "Service Password Incorrect". 

This might be on a later version of BAS but in the screenshots from the developer guide, the "Service Username" and "Service Password" attributes are not available. 

Anyone could support understanding how to make the connection? 
Thank you in advance
Tiago

**Comment by Liebherr** [comment]
Hi Tiago,
sorry for the delay.
Does the problem still persist?
Actually the reason for getting the user and password fields offered was caused by bad error handling in BAS.
After some fixes there should come a better error description that helps you to fix the root cause for the not working SAML connection.
If your problem still persists this way or you are not able to fix it from the given hints please open a ticket to CA-UX-IDE.
Thanks and Regards
Ulrike
