### ISSUE TITLE
Deploy MSSQL in the Kyma Runtime

### ISSUE THREAD

**Issue by dvankempen** [sap-tutorials/Tutorials#18061]
Tutorials: https://developers.sap.com/tutorials/cp-kyma-mssql-deployment.html
--------------------------

Step 6: Locally access the MSSQL Deployment

kubectl get pod mssql-<id> -n dev --template="{{(index (index .spec.containers 0).ports 0).containerPort}}"
returns port 15090 consistently (not expected 1433) 

A connecting to the pod hosted in the SAP BTP Kyma runtime using port-fowarding with local sqlcmd client cannot be established. 

Step 7: Directly access the MSSQL Deployment

Connection is successful. 

==

When deploying Mongodb and running the get pod with template command, the same port 15090 is returned (not expected 27017). Connecting to port 15090 using port forwarding and a local mongodb client is successful. 
 
https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/

**Comment by jcawley5** [comment]
Hello Denys,

The issue is that the container indexing has changed. By default each pod will also have an envoy proxy container within it, used by the service mesh, along with your pod spec. If you adjust the container index to 1 it should return the correct port

kubectl get pod mssql- -n dev --template="{{(index (index .spec.containers **1**).ports 0).containerPort}}"

I will change the tutorial to show the ports of both containers to eliminate the confusion using the command

kubectl get pod mssql- -n dev -o jsonpath="{.spec.containers[*].ports}"

This change will be published within the next weeks.
