### ISSUE TITLE
Add the Consumption of an External Service to Your CAP Application

### ISSUE THREAD

**Issue by guwerner** [sap-tutorials/Tutorials#18087]
Tutorials: https://developers.sap.com/tutorials/btp-app-ext-service-add-consumption.html
--------------------------

Hi experts,

if I run **cds watch** the API_Business_Partner it connect to port **50297** which I have used before. 
Now I start the app again, after I closing other services the main port is now 4004. 
How can I change the port of the other service to port 4004.

`[cds] - connect to API_BUSINESS_PARTNER > odata { url: 'http://localhost:50297/api-business-partner' }`

Part of package.json
` "API_BUSINESS_PARTNER": {
        "kind": "odata-v2",
        "model": "srv\\external\\API_BUSINESS_PARTNER",
        "[sandbox]": {
          "credentials": {
              "url": "https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_BUSINESS_PARTNER/"
           }
        }
      }`

Regards

Gunter

**Comment by manjuX** [comment]
Hi Gunter,

When the 4004 port is not free cds watch will choose a random free port for you. After you add the API key you can verify that the Business Partner service is accessible through the risks service. In the tutorial we create an entity called Suppliers with a few of the Business Partner's properties.

Run `cds watch --profile sandbox`, This is important so that it uses the sandbox profile to connect to the external service.
Next, goto the link `http://localhost:4004/service/risk/Suppliers?$top=11` to see the Response from the business partners service showing only the properties we exposed.

In case you face issues due to the port 4004 being in use you can free the port. To do that on windows run the following command:

`netstat -a -o -n`

This will list the ports and process IDs (PID), note the PID for the 4004 port. Next execute the following command

`taskkill /F /PID <enter the PID here>`.

In case you still face issues please do share the complete package.json and the commands you are using.

Best Regards,
Manjunath
