### ISSUE TITLE
Integrate Charts and Conditional Rendering

### ISSUE THREAD

**Issue by nayyarnishant** [sap-tutorials/Tutorials#18132]
Tutorials: https://developers.sap.com/tutorials/ui5-webcomponents-react-charts.html
--------------------------

**Step 3:** Final code snippet is having an error.

### Error
`CardHeader` is missing in the imports.

```swift
ERROR in src/MyApp.jsx
  Line 52:12:  'CardHeader' is not defined  react/jsx-no-undef
```

### Proposed Snippet Fix:

```diff
import React, { useState } from "react";
- import { Card, Text, Icon } from "@ui5/webcomponents-react";
+ import { Card, CardHeader, Text, Icon } from "@ui5/webcomponents-react";
import { spacing } from "@ui5/webcomponents-react-base";
import { BarChart, LineChart } from "@ui5/webcomponents-react-charts";
import "@ui5/webcomponents-icons/dist/line-chart.js";
import "@ui5/webcomponents-icons/dist/horizontal-bar-chart.js";

const dataset = [
  {
    month: "January",
    data: 65
  },
  {
    month: "February",
    data: 59
  },
  {
    month: "March",
    data: 80
  },
  {
    month: "April",
    data: 81
  },
  {
    month: "May",
    data: 56
  },
  {
    month: "June",
    data: 55
  },
  {
    month: "July",
    data: 40
  }
];

export function MyApp() {
  const [toggleCharts, setToggleCharts] = useState("lineChart");
  const handleHeaderClick = () => {
    if (toggleCharts === "lineChart") {
      setToggleCharts("barChart");
    } else {
      setToggleCharts("lineChart");
    }
  };
  return (
    <div>
    <Card
      header={
        <CardHeader
          titleText="Card"
          interactive
          onClick={handleHeaderClick}
          avatar={ <Icon name={ toggleCharts === "lineChart" ? "line-chart" : "horizontal-bar-chart" } /> }
        />
      }
      style={{ width: "300px" }}
    >
        <Text style={spacing.sapUiContentPadding}>
          This is the content area of the Card
        </Text>
        {toggleCharts === "lineChart" ? (
          <LineChart
            dimensions={[{ accessor: "month" }]}
            measures={[{ accessor: "data", label: "Stock Price" }]}
            dataset={dataset}
          />
        ) : (
          <BarChart
            dimensions={[{ accessor: "month" }]}
            measures={[{ accessor: "data", label: "Stock Price" }]}
            dataset={dataset}
          />
        )}
      </Card>
    </div>
  );
}
```

**Comment by Lukas742** [comment]
Hi @nayyarnishant,

sorry for the late reply, I must have missed your issue. This is actually already fixed in the `master` branch, I don't know why it's not replicated to the Tutorials pages.

@MichaelCzcz could you help out here?

Lines that are not in sync with the `master` branch:
https://github.com/sap-tutorials/Tutorials/blob/f15a65a7bf68c37d67db5a7716e466a9ee4e4eb4/tutorials/ui5-webcomponents-react-charts/ui5-webcomponents-react-charts.md?plain=1#L253
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/9749730/158637991-82b3dbc8-0f92-40d5-9658-20628694907a.png">


https://github.com/sap-tutorials/Tutorials/blob/f15a65a7bf68c37d67db5a7716e466a9ee4e4eb4/tutorials/ui5-webcomponents-react-charts/ui5-webcomponents-react-charts.md?plain=1#L292
<img width="683" alt="image" src="https://user-images.githubusercontent.com/9749730/158638124-6da2c813-0c05-4cd5-ade9-ea28b9d8adf5.png">

It seems like this [commit](https://github.com/sap-tutorials/Tutorials/commit/221547ec665aa576dd4085764978efbcf0a8409d) hasn't made it into the published version.

**Comment by MichaelCzcz** [comment]
@Lukas742 Please update the tags (products -> software-product).
