### ISSUE TITLE
Create and Run Unit Tests for a Fiori App

### ISSUE THREAD

**Issue by AlexMFrank** [sap-tutorials/Tutorials#18172]
Tutorials: https://developers.sap.com/tutorials/abap-environment-qa-unit-tests.html
--------------------------

In step 10, the variable `travel1` doesn't exist and I get a syntax error, if I copy+paste the code. The variable should likely be `travel` or, better, `accepted_travel`.
![grafik](https://user-images.githubusercontent.com/11724820/156651005-2ce37107-773a-4784-a6a3-0ccdbd02eb77.png)

In step 11, I get a syntax error in method `create_travel_not_ok` that `travel_id` can't be modified. It is defined as `read-only` in step 1 of tutorial [https://developers.sap.com/tutorials/abap-environment-behavior.html](https://developers.sap.com/tutorials/abap-environment-behavior.html).
![grafik](https://user-images.githubusercontent.com/11724820/156650886-5815e9bf-f8c4-45aa-be0f-4952bf6479db.png)

In step 11, in the 3rd code part, `/DMO/I_Travel_M` is suddenly used instead of `ZI_Travel_M_XXX`. The `travel_id` issue is also there:
![grafik](https://user-images.githubusercontent.com/11724820/156652468-4cf0a65c-641b-4b1f-a3a2-a5be8581d6dc.png)

**Comment by julieplummer20** [comment]
Hi Alex, 
Re: Step 11: Yes, the tutorial [https://developers.sap.com/tutorials/abap-environment-behavior.html](https://developers.sap.com/tutorials/abap-environment-behavior.html) has been updated. I apologise for the inconvenience.
I will update this tutorial as soon as possible and let you know.
Best wishes,
Julie Plummer.

**Comment by julieplummer20** [comment]
Hi Alex,Hi,
The problem was that this tutorial is based on [https://developers.sap.com/tutorials/abap-environment-behavior.html](https://developers.sap.com/tutorials/abap-environment-behavior.html)
This was updated to make travel_id read-only.
I’ve now updated the code and the tutorial so it should work.
For the present, I simply removed travel_id from the relevant methods.
I will look at creating a more satisfactory longterm solution.

Please let me know if you experience any more problems.
Best wishes,
Julie Plummer.

**Comment by julieplummer20** [comment]
Hi Alex, 
I've looked at this. travel_id should be created automatically, since the service implements the managed scenario.
Therefore, the tutorial should now work.
I will close this issue.
Please feel free to get in touch if you have any other issues.

Thanks and best wishes,
Julie Plummer.
