### ISSUE TITLE
Create a Sample iOS App

### ISSUE THREAD

**Issue by simfer** [sap-tutorials/Tutorials#18293]
Tutorials: https://developers.sap.com/tutorials/fiori-ios-scpms-create-sample-app.html
--------------------------
Hi I've followed the tutorial, but when I try to run the app I get the following error:

/Users/i045523/Library/Developer/Xcode/DerivedData/TutorialApp-abddrxdbloltgzbtxwdmvyddujbc/Build/Intermediates.noindex/TutorialApp.build/Debug-iphonesimulator/TutorialApp.build/Script-AE0C88F42403A2B5002A9565.sh: line 2: python: command not found
Command PhaseScriptExecution failed with a nonzero exit code

![immagine](https://user-images.githubusercontent.com/6877529/161507253-4b4a0157-d39b-4fc6-bbab-344a19998f04.png)

But Python is correctly installed.
![immagine](https://user-images.githubusercontent.com/6877529/161507495-33cdbd6c-877a-4226-9d14-48e683a8f4cd.png)

How to fix it?

Simmaco

**Comment by simfer** [comment]
Furthermore if I try to run the script manually, I get this:

![immagine](https://user-images.githubusercontent.com/6877529/161512500-8d67c848-5c7c-4a44-b361-0ac3ce337f14.png)

Simmaco

**Comment by krishnamurthy5111** [comment]
Hi @simfer , Python 2.7 was removed from macOS in the 12.3 [update](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes). Due to this, for the projects that get generated with the SAP BTP SDK for iOS 7.0.2 or below need to make a small modification to fix the error that is coming above.

You need to go to the Codesign Binaries build phase as shown below and change python to python3.
<img width="1387" alt="Screenshot 2022-04-06 at 7 38 07 PM" src="https://user-images.githubusercontent.com/7485000/161994895-00b34674-9397-4e8d-86dc-53bc873a78e4.png">

If you are planning to run the project on mac catalyst, then you need to make this additional change in codesign.py file available at projectFolder/scripts/: (92nd line)
if err.find("ambiguous") != -1:    --->    if err.find(b"ambiguous") != -1:

**Comment by simfer** [comment]
Thanks this fixed my issue.

Simmaco
