### ISSUE TITLE
Create an API Proxy

### ISSUE THREAD

**Issue by gitbenedict** [sap-tutorials/Tutorials#18299]
Tutorials: https://developers.sap.com/tutorials/hcp-apim-create-api.html
--------------------------

Write here how you think we can improve the tutorial ...
The correct answer to the question Does an API Proxy contain any functionality?, is given as 'No'

But in this blog [](https://blogs.sap.com/2016/06/17/part-1-introduction-to-api-management/) it is explicitly stated "An API Proxy is the data object that contains all the functionality to be executed..."

**Comment by kulkarnir** [comment]
Hello, 

Yes, it is a tricky question. we call this an API **Proxy**. and you will be accessing the proxy end point.

Ans is correct No,  because you are accessing the proxy endpoint, and it sends your request to the actual endpoint to get the expected response.

Having said that, we can manage the API Proxy by adding traffic management policies like quota or securing the API Proxy using our security policies, etc 

Hope I answered the query

Regards,, Raghu

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
