### ISSUE TITLE
Integrate Charts and Conditional Rendering

### ISSUE THREAD

**Issue by songyu-Ren** [sap-tutorials/Tutorials#18722]
Tutorials: https://developers.sap.com/tutorials/ui5-webcomponents-react-charts.html
--------------------------
Dear Developers,

I think the commit ``npm install @ui5/webcomponents-react-charts --save`` have some problems. I am trying to do the hands on, but my computer cannot render the Barchart and the LineChart. 

But if I use ``npm install @ui5/webcomponents-react-charts``, the chart can be rendered. 

Best regards,
Songyu

**Comment by Lukas742** [comment]
Hi @songyu-Ren 

the `npm` command should have nothing to do with the actual rendering of the chart. Npm is used here to install the `@ui5/webcomponents-react-charts` package. Before version 5 of npm you had to use the `--save` parameter to automatically add the package name to the dependencies (`package.json`), for newer versions this parameter isn't necessary anymore as `npm install <package-name>` adds it even without the parameter. 
I kept it in the Tutorial, as it doesn't hurt to add the parameter and is easier for users with an old npm version.

So your rendering problem should have another root cause.

**Comment by songyu-Ren** [comment]
Dear Lukas,

Thank you so much for helping. I am going to check my root. 

Best regards, 
Songyu

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
