### ISSUE TITLE
Tour the SAP Community 2022

### ISSUE THREAD

**Issue by daniel-maayan** [sap-tutorials/Tutorials#18745]
Tutorials: https://developers.sap.com/tutorials/community-2022.html
--------------------------

Im trying to follow a tag like mentioned in topics - but it just keeps me signed off, and when i try to sign up it just refreshes the page without letting me to sign in so ill be able to follow a topic.

done in brave browser - checked in firefox as well.

**Comment by daniel-maayan** [comment]
after further testing - it's fixed if i go into incognito mode - however the topic i tried to follow - SAP Business Application Studio - doesn't have the option to follow it
![image](https://user-images.githubusercontent.com/108078070/187074086-8c877ccf-c30a-456e-a572-4152d14ec479.png)

**Comment by daniel-maayan** [comment]
further addition - to find the BAS topic with the ability to follow it - i couldn't find it from the topics section - however if i pressed on a blog post with the tag of SAP Business Application Studio - it sent me to the correct link with the ability to follow that topic:
https://answers.sap.com/tags/67837800100800007077 - its not under community.sap.com but rather answers.sap.com

**Comment by lenastodal** [comment]
Hi @daniel-maayan - thank you for comments and feedback. 
1.) By now, the issue with the tags should be resolved. Can you please confirm if you're still facing the issue? If so, I will report back to our IT team. 
2.) The follow opportunity doesn't appear, because the SAP Business Application Studio topic page is still in the "old topic page template" which doesn't have the same tag follow ability as the "new topic page template". I will reach out to the topic page owner to check on the migration to the new one. 
3.) You're correct, you can follow a tag from either answers.sap.com or blogs.sap.com // https://answers.sap.com/tags/67837800100800007077 and https://blogs.sap.com/tags/67837800100800007077 (67837800100800007077 is the respective tag number for BAS). 
Thank you, 
Lena

**Comment by MichaelCzcz** [comment]
@daniel-maayan Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
