### ISSUE TITLE
Open SAP Web IDE for SAP HANA Development

### ISSUE THREAD

**Issue by russellw999** [sap-tutorials/Tutorials#18777]
Tutorials: https://developers.sap.com/tutorials/webide-multi-cloud.html
--------------------------

Write here how you think we can improve the tutorial ...

The steps in the studio referring to WebIde seem to be outadated as WebIde no longer exists in the trail having been replaced by Business Application Studio

**Comment by jung-thomas** [comment]
Which is why this tutorial is marked the following disclaimer: "This tutorial cannot currently be completed with a trial account." And it is classified as "Requires Customer/Partner License".

The tutorial remains in the system for customers/partners that have a productive account in which they are still using the SAP Web IDE. Admittedly a small segment as Business Application Studio is recommended; but we felt it best to keep the instructions for those that are still using the old tools under their existing license.
