### ISSUE TITLE
Connect Your AppGyver Application to a Public API

### ISSUE THREAD

**Issue by mohamedyosufdeenjmh** [sap-tutorials/Tutorials#18887]
Tutorials: https://developers.sap.com/tutorials/appgyver-connect-publicapi.html
--------------------------

In the question at the very end of Step 3, one option reads **"Wheat flower"**. It must be **"Wheat flour"**.

**Comment by thecodester** [comment]
Done - https://github.com/sap-tutorials/Tutorials/commit/64cd7dbbdd65eadc052dda98357c437cb1da4fcf

I'm really bad with homonyms - I should know better because I read an Encyclopedia Brown case where EB found the bad guy because he knew the stolen jewel was hidden by the criminal in the flour pot, but EB told the guy to hold a flower pot. So EB had the bad guy hold a "flower pot" and then asked him to search for the jewel in the "flower pot", but the bad guy -- despite holding a "flower pot" -- went immediately for the "flour pot" ... or something like that.
