### ISSUE TITLE
Consume SAP BTP Services In SAP Kyma

### ISSUE THREAD

**Issue by SatheesP** [sap-tutorials/Tutorials#18937]
Hello Team,

Tutorials: https://developers.sap.com/tutorials/btp-kyma-extension.html
--------------------------

I am using Windows 10 PC and in this tutorial,  following note
Note: Incase of login fails run command “kubectl krew install oidc-login”.

getting following error
error: unknown command "krew" for "kubectl"

next steps what should I do ?? Tutorial doesn't provide more info. about how to handle **krew**

I added issue to [krew](https://github.com/kubernetes-sigs/krew)
https://github.com/kubernetes-sigs/krew/issues/808

-Sathees

**Comment by shivakumar-p12-sap** [comment]
Hi Sathees,

Please install and configure krew https://krew.sigs.k8s.io/docs/user-guide/setup/install/ . It is mentioned in the Prerequisites section. After installation run this command "kubectl krew install oidc-login". This is required due to the update in kyma environment.

Best Regards,
Shivakumar P

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
