### ISSUE TITLE
Import SAP SuccessFactors OData Services definitions

### ISSUE THREAD

**Issue by rcaziraghi** [sap-tutorials/Tutorials#20834]
Tutorials: https://developers.sap.com/tutorials/cap-extend-sfsf-import-services.html
--------------------------

Hello and happy holydays!

In step 4 we bind destination and XSUAA service instances to the local CAP project using a "default-env.json" file. However, the "default-env.json" file configuration is deprecated (please see https://cap.cloud.sap/docs/node.js/cds-env#in-default-envjson ). Now we should use "cds bind" with "cds watch --profile hybrid". The tutorial still works though.

Please let me know if I can be of further help!

Thank you.

Rafael Caziraghi

**Comment by ale-biagi** [comment]
Happy Hollydays!

By the time this tutorial was written **default-env.json** was the only option for local project binding. Although the method is deprecated by means of continuous enhancements in the cds framework it will continue to be supported indefinitely due to backward compatibility with legacy projects (which is the case of the tutorial). As other enhancements are planned for the CAP roadmap we will do the corresponding updates in the affected tutorials at once in the appropriate time.

Thanks,

Alessandro

**Comment by rcaziraghi** [comment]
Happy New Year Alessandro!
Thank you so much for creating such a useful tutorial. It has been incredibly helpful to me. I will definitely be looking out for updates on your tutorials in the future. 
Wishing you all the best in the new year!
