### ISSUE TITLE
Enhance an ABAP Core Data Services (CDS) View in SAP Business Technology Platform (BTP) ABAP Environment

### ISSUE THREAD

**Issue by alwinvandeput** [sap-tutorials/Tutorials#22751]
Step 5 is missing 2 lines

      @Semantics.amount.currencyCode: 'UsdCurrency'
      currency_conversion( ...

      cast( 'USD' as abap.cuky )                                as UsdCurrency,

STEP 9 Specify hierarchy is empty

**Comment by julieplummer20** [comment]
Hi [alwinvandeput](https://github.com/alwinvandeput),
Thanks for getting in touch.

Here is the code in step 5:

`    @Semantics.amount.currencyCode: 'CurrencyCode'
    currency_conversion(
     ...
    target_currency => cast('USD' as abap.cuky( 5 )),
    exchange_rate_date => cast('20200429' as abap.dats),
    error_handling => 'SET_TO_NULL' )
    as PriceInUSD, ` 

So what "missing 2 lines" are you referring to? The issue is not clear.

Step 9: I have updated the text. The changes should appear within 48 hours.
Best wishes,
Julie.

**Comment by julieplummer20** [comment]
Hi Alwin, Since I haven't heard from you, I shall close the issue.
Best wishes,
Julie.
