### ISSUE TITLE
Create a Python Application via Cloud Foundry Command Line Interface

### ISSUE THREAD

**Issue by joschkarick** [sap-tutorials/Tutorials#22894]
Tutorials: https://developers.sap.com/tutorials/btp-cf-buildpacks-python-create.html
--------------------------

In the current cf trial environment python 3.10.1, which is used in this tutorial, is not available for building.

 **ERROR** Could not install python: no match found for 3.10.1 in [3.7.15 3.8.15 3.9.15 3.10.8 3.11.0]

**Comment by Joysie** [comment]
Hi @joschkarick,

Thank you for your contribution! That was a very timely comment - I just updated the tutorial so now it's working better and is applicable for trial accounts as well.

Unfortunately, the constantly changing versions supported by every next Python buildpack release is tricky and sometimes annoying, I admit! Your error is due to the fact that the latest Python buildpack version supported by SAP BTP, Cloud Foundry - [v1.8.3](https://github.com/cloudfoundry/python-buildpack/releases/tag/v1.8.3) - no longer contains Python version _3.10.1_. (You can check current buildpack versions by executing: **cf buildpacks**)

**What you can do:**

1. Install Python **3.11.1**. This is going to be the new version to be released next week and is going to be supported for at least few months ahead. 

2. Since it's not present in "our" buildpack version yet, in the _runtime.txt_ file, you can set:

   **python-3.11.0**

It's working fine this way - I tested it.

Let me know if it works for you too! 🙂

Best regards,
Gergana

**Comment by jmmargo** [comment]
As a solution was provided, I am closing this issue.
