### ISSUE TITLE
Load Data into Standalone Data Lake in SAP HANA Cloud

### ISSUE THREAD

**Issue by ahmedkhan29789** [sap-tutorials/Tutorials#22937]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-hdl-getting-started-3.html
--------------------------

In this tutorial, It doesn't clearly show if the data has been stored in HANA DATA LAKE or in HANA Cloud, We always have two options in HANA i.e HANA CLOUD and HANA DATA LAKE, How could i make sure that for these tables I have used HANA DATA LAKE memory and not of HANA Cloud?

**Comment by danielva** [comment]
SAP HANA Cloud is the broad product name that encompasses both the SAP HANA Cloud, SAP HANA Database an in-memory database and SAP HANA Cloud, SAP HANA Data Lake Relational Engine a columnar disk based database.  
The SAP HANA database explorer and the database objects app in SAP HANA Cloud Central enable you to connect to a data lake Relational Engine (or a HANA database) and view the different objects such as a table and include runtime information such as the number of records in the table.  

It is also possible for an SAP HANA Cloud, SAP HANA Database to make use of Native Storage Extensions to specify that a subset of the data in a table should be left on disk rather than being loaded into memory.  See step 4 of https://developers.sap.com/tutorials/hana-dbx-create-schema.html.

Sorry for the delay in responding.

**Comment by ahmedkhan29789** [comment]
I am sorry to let you know that the question what i have asked originally was not answered.

Let me try to rephrase it, When i should choose hana cloud or hana data lake for my development, does hana cloud and hana data lake share same hana database and same instance?

**Comment by danielva** [comment]
The SAP HANA database is different from a data lake Relational Engine database.  It is possible though to connect and access the data from a data lake Relational Engine database in an SAP HANA database.

https://help.sap.com/docs/hana-cloud/sap-hana-cloud-getting-started-guide/sap-hana-cloud-components contains more details.   

The data lake Relational Engine provides high-performance analysis for petabyte volumes of relational data.  So this is great for data that you wish to query and store but perhaps are not frequently updating whereas the SAP HANA database can be used as both a transactional and analytic database.
