### ISSUE TITLE
CAP Development Tutorial: Deploy Your Multi-Target Application (MTA) - declaring role

### ISSUE THREAD

**Issue by js1972** [sap-tutorials/Tutorials#22938]
Tutorials: https://developers.sap.com/tutorials/btp-app-cap-mta-deployment.html
--------------------------

In this tutorial you declare security information directly in the mta file instead of in xs-security.json. The reason given is that this allows you to prefix your security artefacts with a suffix of the space name like "-dev", etc.

But is this best practice? In general with working in BTP the best practice is to work at the subaccount level and not use spaces. This is generally due to the fact that many BTP services are not at all space-aware.  So your dev, test and prod layers would be separate subaccounts and not spaces.

Therefore would it not also be best practice to use the xs-security.json to specify security info instead of putting it into the mta.yaml?

![image](https://user-images.githubusercontent.com/1317161/225781804-ef750526-3fe0-4ea7-a7cd-aad8b9d6e5f5.png)

**Comment by manjuX** [comment]
Hi @js1972,

Thank you for trying our tutorial and providing your feedback. In the tutorial the developer configures the XS-security file, it also shows how the configuration can be overridden in the mta.yml. Spaces can be used to allow developers to share resources during development which might be due to cost or maintenance overhead.

We will try to make it more clear that this should not be done for production as a hint or note.

Thanks and best regards,
Manju

**Comment by slavipande** [comment]
Hi @js1972 ,

Thanks for pointing this out!

We've updated the description in this step to make it more clear that (1) For a productive application, the configuration for XSUAA should be read from the `xs-security.json` file and (2) XSUAA configuration that is read from the `xs-security.json` file can be overwritten in the `config` element of the `mta.yaml` file but this is done within the scope of this tutorial to allow multiple deployments in different spaces of the same subaccount. 
Changes should be visible soon.

Hence, I'll be closing this issue.

Best regards,
Svetoslav
