### ISSUE TITLE
Prepare Your Development Environment for CAP

### ISSUE THREAD

**Issue by bipinm** [sap-tutorials/Tutorials#22970]
Tutorials: https://developers.sap.com/tutorials/btp-app-prepare-dev-environment-cap.html
--------------------------

Step 16 says - The name of the prerequisite branch is given on the top of each tutorial that requires code changes., but this is not true. 
There are so many branches in the tutorial, not sure which one is to be checked out

The step is actually optional and this must be stated explicitly. I could figure this out only when i decided to proceed to next steps - [Create a CAP-Based Application](https://developers.sap.com/tutorials/btp-app-create-cap-application.html). IMHO, The step is completely un-necessary because if someone decides to do this, rest of tutorial might not work properly as well. The "DONE" button must be removed then ?

**Comment by manjuX** [comment]
Hi @bipinm ,

Thank you for your feedback. We provide the branch names only in the local development part because for the rest of the Mission you need to work through all the tutorials mentioned in the pre-requisites. For example if you directly checkout the branch for the tutorial 'Prepare User Authentication and Authorization (XSUAA) Setup' and try to deploy the project it would fail, because you would need to have done the previous tutorials to setup the SAP Hana instance on the cloud.

Unfortunately the Developer Portal does not allow us to remove the DONE button for optional steps and that is a limitation that we cannot work around.

Best regards,
Manju

**Comment by smahati** [comment]
Hi, We've added the steps as optional so I'll close this issue. Please open a new issue if you need further assistance with the tutorial.

Best regards,
Mahati
