### ISSUE TITLE
Configure SAP Build Application to Open Device Camera

### ISSUE THREAD

**Issue by maxime-foulon** [sap-tutorials/Tutorials#23095]
Tutorials: https://developers.sap.com/tutorials/appgyver-configure-camera.html
--------------------------

On the test when we need to scan the barcode, the response is uncorrect but i can read the barcode with the application, fix it please

**Comment by jmmargo** [comment]
Daniel, can you please help this user?

**Comment by thecodester** [comment]
@maxime-foulon What is incorrect?

I just completed and it works fine. I can only imagine that the issue you raise is that screenshot above does not reflect the number in the barcode we gave as an example. That is true, and I can sort of see the confusion you may have, but the tutorial says to go out and scan your own barcodes, and provides the screenshot as an example. We give a barcode in case you do not want to walk to your pantry.

If the issue is something else, then I apologize. Please explain again what is the matter.

**Comment by jmmargo** [comment]
As there has been no follow up, I will assume the issue is resolved.  Please reopen if necessary.
