### ISSUE TITLE
Create a CAP-Based Application

### ISSUE THREAD

**Issue by flaviuskehr** [sap-tutorials/Tutorials#23153]
Tutorials: https://developers.sap.com/tutorials/btp-app-create-cap-application.html
--------------------------

Hi, just went through this tutorial incl. the necessary setup pre-steps. Worked fine so far (took me 30 minutes in total), there are two things that didn't quite work for me as described in the tutorial:

1) for some reason npm only worked for me with root privileges activated. Tried a couple of times without, then used "sudo" to install UI5 and other components and it finally worked.
2) http://localhost:4004/service/risk/Risks - is not a valid path in my server instance. http://localhost:4004/odata/v4/service/risk/Risks - works, instead.

**Comment by smahati** [comment]
Hi Flavius,

Sorry we didn't reply to your issue sooner,

1) Sudo might work but will cause issues later in the tutorial, I would suggest finding a solution instead. For example, [node version manager](https://github.com/nvm-sh/nvm#install--update-script)(nvm) can help you manage the installation. After you install it you can run the following two commands to install the latest lts:
```zsh
nvm install --lts
nvm use --lts
```
2) Thanks for pointing this out, this was due to an update and we'll update it.

Best regards,
Mahati

**Comment by smahati** [comment]
closing as we haven't had activity on this issue for a while. Please create another issue if you need support.

Best regards,
Maha
