### ISSUE TITLE
Set Up SAP Business Application Studio for Development

### ISSUE THREAD

**Issue by MurkuteNidhi** [sap-tutorials/Tutorials#23252]
Tutorials: https://developers.sap.com/tutorials/appstudio-onboarding.html
--------------------------

Step 5 & 6 : After manually subscribing the SAP Business Application Studio, user should add his/her ID to the required role collection to access SaaS.
Please add this step to the tutorial.

**Comment by raz-korn** [comment]
Hi @MurkuteNidhi ,

The tutorials are designed to be used in a trial environment.
In this case, when using the subaccount that is created as part of the registration to trial, there's no need to manually subscribe to BAS nor add role collections.

Regards - Raz

**Comment by MurkuteNidhi** [comment]
Hi @raz-korn ,
Yea, when newly setting up subaccount it would setup all things.
The above issue was - when no subscription added as shown in Step5: So in this case as well no need to add role collections? But as shown in step6 screenshot it shows access denied and asked to logout and login to reflect the assigned roles.

**Comment by raz-korn** [comment]
Hi @MurkuteNidhi 
If you want to use BAS in a trial environment, you should follow the [Get a Free Account on SAP BTP Trial](https://account.hanatrial.ondemand.com/trial/#/globalaccount/589aff1a-107e-4556-a368-019f01edbc29/accountModel&//?entityGuid=589aff1a-107e-4556-a368-019f01edbc29&section=SubaccountsSection&view=TilesView). This will result in a subaccount where you can use BAS without manual configuration.
If you use an Enterprise Account, you should refer to the text directly below the Prerequisites section.
It contains a link to the steps needed in order to setup BAS in an Enterprise Account.

Regards - Raz
