### ISSUE TITLE
Change is required on Tutorial : Deploy Your Business Application to Cloud Foundry 

### ISSUE THREAD

**Issue by yilmazozkan** [sap-tutorials/Tutorials#23407]
Tutorials: https://developers.sap.com/tutorials/appstudio-cap-deploy-app.html
--------------------------

Hi, 
This tutorial should be modified. Because `hdi-shared` plan belongs only to SAP HANA Schemas & HDI Containers (hana), not Trial 
 (hanatrial) anymore. Change on these parts is necessary:
1.
![image](https://github.com/sap-tutorials/Tutorials/assets/44052044/ae575975-ddf9-424f-9dc6-6ab0fa958d40)

2. ![image](https://github.com/sap-tutorials/Tutorials/assets/44052044/77ad9f52-cc63-4449-8385-31c0fe3a1ccb)

See BTP Instance creation to verify:
![image](https://github.com/sap-tutorials/Tutorials/assets/44052044/368d8e07-2c5b-4ce0-8afb-6d984c6c32db)

![image](https://github.com/sap-tutorials/Tutorials/assets/44052044/e33cd151-8af0-4d5f-9b11-978675d1269c)

**Comment by Paolaufer** [comment]
@ShiraManas could you please look into this?

**Comment by ShiraManas** [comment]
Hi, @yilmazozkan. Thanks for the feedback. I've looked into this in the SAP BTP cockpit and propose the following changes to the tutorial:
In the Prerequisites:
In #3, I will change to **SAP HANA Schemas & HDI Containers** (I will remove “Trial”)
In #4 I will provide an updated image:
<img width="791" alt="image" src="https://github.com/sap-tutorials/Tutorials/assets/49026740/db03360d-f445-4de8-8b0c-58c27c07abed">

In the note in Step 3.1, I will change the service parameter to **hana** (instead of hanatrial) to match the service name.

Can you tell me if this is correct and if anything is missing?
Thanks!

**Comment by ShiraManas** [comment]
I've updated the tutorial with the changes listed above and I am now closing the issue. https://developers.sap.com/tutorials/appstudio-cap-deploy-app.html
