### ISSUE TITLE
Create a CAP Application and SAP Fiori UI

### ISSUE THREAD

**Issue by js1972** [sap-tutorials/Tutorials#23493]
Group: https://developers.sap.com/group.btp-app-cap-create.html
--------------------------

Hello.  This tutorial is marked as a "NEW" tutorial on developer.sap.com, however when you try each of the tutorial groups within they all say these tutorials are old and will be removed soon.

**Comment by smahati** [comment]
Hello @js1972 ,

Thank you for reaching out for clarification, the group was indeed modified recently but it was a refactor and due to this the platform marks the group as "new". We will maintain the tutorials to be in a usable state as long as they are on the tutorial navigator and provide support, but as the message states, I would recommend looking at the other missions mentioned as they are more current.

I hope this helps clarify your question.

Best regards,
Mahati
