### ISSUE TITLE
Use Trial to Extract Information from Custom Documents with Generative AI and Document Information Extraction

### ISSUE THREAD

**Issue by cabhishekin** [sap-tutorials/Tutorials#23521]
Tutorials: https://developers.sap.com/tutorials/cp-aibus-dox-ui-gen-ai.html
--------------------------

I understand a schema created is essentially a data structure, which is then used to create a document of certain "document type". Question is lets say i would like to push this document to a S4HANA system, can I 'import' these documents ? All i want is to create document info records (object of Document Management System). Could you please guide me if this is feasible
thanks
abhishek

**Comment by Juliana-Morais** [comment]
Hi Abhishek,

I apologize for the late reply. This issue has been assigned to me only recently.

Since this is a technical question unrelated to the tutorial content, please use the link below to raise your question in the SAP Community so the most suitable colleague gets back to you ASAP. Make sure to use the SAP Managed Tag: "Document Information Extraction" in your post.

https://community.sap.com/t5/forums/postpage/category-id/products/choose-node/true

Thank you and best regards,
Juliana Morais
