### ISSUE TITLE
Set Up Integration Suite Trial

### ISSUE THREAD

**Issue by FernanDoylet** [sap-tutorials/Tutorials#23540]
Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html
--------------------------

In Step 4 #4 please include: 
On the Space field, select: dev

At https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html
the first graphic in Step 3 shows the instance in the 'dev' space.
Using another space I couldn't apply the Policy Template: Cloud_Platform_Connectivity

**Comment by Karunaharan** [comment]
Hi @FernanDoylet,
Exactly. You won't be able to apply the policy template from another space. Your Integration suite subscription is always associated with a single space.
I don't think it will be appropriate to mention in step 4 of https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html to select the "dev" space, because you can define any name of your choice. That's why it is currently mentioned as "**_select your subaccount, organization, and space in which you have subscribed for Integration Suite service_**".

Hope this helps.
