### ISSUE TITLE
Create ABAPDoc Comments in Your Class

### ISSUE THREAD

**Issue by GirodFred** [sap-tutorials/Tutorials#4078]
Tutorial URL: https://developers.sap.com/tutorials/abap-dev-create-abapdoc.html

Please specify the step you are referring to

The test yourself is realy difficult to achieve. It is case sensitive, it takes me long time to understand I have to write strickly the explanatory text.  Maybe the comment should be 
"Create an ABAPDoc comment for the parameter "planetype", the explanatory text must be "Type of plane"."

**Comment by thecodester** [comment]
@GirodFred Actually, the test yourself is NOT case sensitive, and extra white space is also ignored. But I understand your basic issue.

@julieplummer20 Can you address?

**Comment by julieplummer20** [comment]
Done

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by smtpsantiago** [comment]
Hi Guys.
how resolved this? i tried -> 
`"! @parameter planetype | <p class="shorttext synchronized"> Type of plane </p>`
and
`"! @parameter PLANETYPE | Type of plane`
appears this message -> "Sorry, that’s not quite right.".

what is wrong?

**Comment by julieplummer20** [comment]
Hi, 
Odd. The correct answer is:

"! @parameter PLANETYPE | <p class="shorttext synchronized">Type of plane</p>

I am sorry you are having issues. I will clarify this with the tutorials support team.

BTW - next time, could you perhaps open a new comment, rather than jumping on an old one?
We may be able to react faster.
THanks,
Julie Plummer
ABAP PM.
