### ISSUE TITLE
Create a Simple OData Service with Mobile Back-End Tools

### ISSUE THREAD

**Issue by toddmfisher** [sap-tutorials/Tutorials#7289]
Tutorials: https://developers.sap.com/tutorials/cp-mobile-backend-tools-simple-odata.html
--------------------------

You Cannot have an application name that starts with a number. In the step where you execute command "MBT: Create tasks.json file" the instructions say to name your application with your <subaccount><space> prefix. My Subaccount is "3aeb....".  There is no error message, the wizard just does not advance until you enter a alpha in the first character.  Also, the wizard is blank (no instructions) on the wizard before you start typing. Unless you have the tutorial steps, you would not know. 
Thank
![2021-12-06_17-15-17](https://user-images.githubusercontent.com/50836320/144931505-ce5fb67c-dea6-4288-9927-cfe9e72b0592.png)
![2021-12-06_17-15-17](https://user-images.githubusercontent.com/50836320/144931536-bd0c1644-0aa3-4e10-8674-75bbad4e561a.png)
s!

**Comment by Manuel-Stampp** [comment]
Dear @toddmfisher 
Thank you for reporting this issue. Please excuse late feedback- I'm still working on re-structuring and simplifying the whole tutorial mission and will fix this issue on the way.
The updates are currently in QA and as soon as we roll out a new MBT version in Business Application Studio, we'll conduct final testing in order to fix the reported issue.
